### ISSUE TITLE
Blip function

### ISSUE THREAD

**Issue by Hampfh** [Hampfh/Datapack_SurvivalGames#10]
When the function is called it will reveal players every x second in order to force engagement

**Comment by Hampfh** [comment]
It could be useful to use the `schedule` command here in order to loop the occurrence of the glow. I think the way to go is to keep looping as long as a variable is set to true, then stop the scheduling when the variable is disabled again.

**Comment by Geoffry-Skionfinschii** [comment]
Commented
That sounds like a good idea, i'll look into schedule, thanks for the pointer.
I'll design the functions for the blink, and then piggyback off how you design the late game detection to fully implement it :)

**Comment by Hampfh** [comment]
I've now integrated two hooks into the datapacks for you to use. One is before the "end game" starts and one is when endgame finishes (and sudden death begins) 
![image](https://user-images.githubusercontent.com/30767818/83650965-3f6f1a00-a5b9-11ea-9515-e88686795bed.png)
![image](https://user-images.githubusercontent.com/30767818/83651061-5a418e80-a5b9-11ea-9ec5-ecc1d70b1732.png)

**Comment by Geoffry-Skionfinschii** [comment]
Ok awesome, will implement them this afternoon

**Comment by Hampfh** [comment]
Hi Geoffry! Have you done any progress? No stress I'm just curious

**Comment by Geoffry-Skionfinschii** [comment]
Hi, sorry, had a bunch of work stuff come up, i should *hopefully* have it done tomorrow night, if its still not done by then i might need to yield it back to you, sorry about the runaround.

**Comment by Hampfh** [comment]
Fixed the blip function
