### ISSUE TITLE
OPTION: Airstrikes

### ISSUE THREAD

**Issue by Hampfh** [Hampfh/Datapack_SurvivalGames#14]
At some moment, a bunch of ender dragons fly quickly through the sky and drops tagged things and summon primed TNTs

**Comment by hainam333** [comment]
May be the dragons will drop fireballs down and explode?
/summon fireball ~ ~1 ~ {ExplosionPower:4,direction:[0.0,-2.0,0.0]}
                                                    ^                                         ^
                                      the explosion power                     how fast fireball will travel

**Comment by hainam333** [comment]
ah yes, may be we replace airstrikes with meteor shower?
