### ISSUE TITLE
No loot chest found

### ISSUE THREAD

**Issue by hainam333** [Hampfh/Datapack_SurvivalGames#19]
I activated loot crates but when in game I still can't find any chest or barrels. May be with the coding? I saw the first line in tier json file write chest but in mcfunction files it writes barrel.

**Comment by Hampfh** [comment]
hi from my experience there aren't any problems with this feature however there are not very many loot chests. The chests are generated on a per player basis and I think it's currently configured to spawn one chest per player, that value might need tweaking.

You can find the chest by teleporting to its anchor. There should be an armor stand at its position named "LOOT_CHEST" i think. If you cannot find it I'll try to investigate it when I have time

**Comment by hainam333** [comment]
how to teleport to the armor stand anyway?

**Comment by Hampfh** [comment]
you would do it like this (I have not type cheched this command but you get the general idea)
```
tp @s @e[type=armor_stand, name="LOOT_CHEST",limit=1]
```
