### ISSUE TITLE
New sign editing feature breaks the datapack in versions 1.20+

### ISSUE THREAD

**Issue by SmokePuddingEveryday** [Hampfh/Datapack_SurvivalGames#23]
Title. I understand the datapack is depricated now so I don't expected anything to get fixed, but there still isn't a datapack like this that exists so if anyone has a solution to using the signs on versions after 1.19 please let me know. 

As fas as I know, everything else about the datapack works perfectly fine, but many signs are no longer interactable due to this new feature. I'm not sure if there's a way to get the same functionality of the sgins by using in-game commands.

**Comment by Hampfh** [comment]
Hi! If you can point me to the source of these changes I might me able to take a look. I'm not actively playing Minecraft anymore but performing this fix shouldn't be too problematic given that I know what to look for

**Comment by Hampfh** [comment]
@SmokePuddingEveryday this is now fixed, enjoy :)

**Comment by jackko101** [comment]
Hey Hampfh, just wanted to give a heads up about the sign issue that is still presistent in versions 1.20+. gave myself the Moderator tag and everything. I know you're not actively playing Minecraft but thought I would let you know!
