### ISSUE TITLE
Variable playing area

### ISSUE THREAD

**Issue by Hampfh** [Hampfh/Datapack_SurvivalGames#5]
It should be possible to change the size of the worldborder & shrink time as a setting. Preferably completely custom but otherwise predefined steps could also work.

**Comment by Geoffry-Skionfinschii** [comment]
Steps of 100 blocks away from center would probably be granular enough to feel good

**Comment by Hampfh** [comment]
I did consider having small steps however as settings are managed with signs the option count can't be too high as that would require the user to click too many times.
I thought that maybe in terms of size you could have a scale like this (diameter):
500
1000
2000
4000
This way it's easy to cycle through and the player has some freedom for customization. The weird thing is that minecraft does not allow for variable arguments when setting the border so it has to be hard-coded

**Comment by Hampfh** [comment]
I settled on the following options for map sizes (diameter):
50,100,200,400,800,1600 and 3200
For game duration, there are settings form 15 min to 120 min with an interval of 15 minutes between each setting
